### ISSUE TITLE
Missing 'CudaDnnDll.8.dll' from nuget

### ISSUE THREAD

**Issue by YanYas** [MyCaffe/MyCaffe#6]
Running the project, I get this error for a file that hasn't been installed. Other versions of the CudaDnnDll are installed so I guess it just wasn't included in the Nuget?

`
Failed to load 'C:\Program Files\vvvv\vvvv_gamma_2019.1.0-0975-gbe94390fc5\CudaDnnDll.8.dll'!
   at MyCaffe.common.CudaDnn`1..ctor(Int32 nDeviceID, DEVINIT flags, Nullable`1 lSeed, String strPath, Boolean bResetFirst, Boolean bEnableMemoryTrace)
   at MyCaffe.MyCaffeControl`1.LoadLite(Phase phase, String strSolver, String strModel, Byte[] rgWeights, Boolean bResetFirst, String strStage, Boolean bEnableMemTrace)
   at Main.ExploringmyCaffe2Application.UpdateDEBUG(PatchTracer tracer) in C:\Users\Igor\Documents\TFProjects\_In-House\VLMyCaffe\ExploringmyCaffe2.vl:line 185248`

![image](https://user-images.githubusercontent.com/9497052/70168133-2516bb00-16c0-11ea-904b-db1286b012c8.png)

![image](https://user-images.githubusercontent.com/9497052/70167870-8a1de100-16bf-11ea-878b-74411d5ada5d.png)

**Comment by YanYas** [comment]
Hi again. Should CudaDnnDll.8.dll have been packaged with the Nuget, or should it be unnecessary?

**Comment by YanYas** [comment]
My apologies, I've looked further into it and discovered there is a problem with the setup of my new IDE, It couldn't identify the placement of the native dlls from the Nuget.
